"""комментарий к оценке

Revision ID: aa15bf2bc6a8
Revises: 1ed715a23a9f
Create Date: 2020-06-04 10:43:28.356248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa15bf2bc6a8'
down_revision = '1ed715a23a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('comment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'comment')
    # ### end Alembic commands ###
