"""Первая миграция

Revision ID: 1ed715a23a9f
Revises: 
Create Date: 2020-06-02 16:40:14.408830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed715a23a9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('prepod_id', sa.Integer(), nullable=True),
    sa.Column('zan_type', sa.String(length=12), nullable=True),
    sa.Column('groups', sa.String(length=10), nullable=True),
    sa.Column('dz', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_date'), 'schedule', ['date'], unique=False)
    op.create_index(op.f('ix_schedule_groups'), 'schedule', ['groups'], unique=False)
    op.create_index(op.f('ix_schedule_prepod_id'), 'schedule', ['prepod_id'], unique=False)
    op.create_index(op.f('ix_schedule_zan_type'), 'schedule', ['zan_type'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('patronymic', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('groups', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_groups'), 'user', ['groups'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_patronymic'), 'user', ['patronymic'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('prepod', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_date'), 'grades', ['date'], unique=False)
    op.create_index(op.f('ix_grades_prepod'), 'grades', ['prepod'], unique=False)
    op.create_index(op.f('ix_grades_user_id'), 'grades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grades_user_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_prepod'), table_name='grades')
    op.drop_index(op.f('ix_grades_date'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_patronymic'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_groups'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_schedule_zan_type'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_prepod_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_groups'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_date'), table_name='schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###
